### ISSUE TITLE
remove LogEntry

### ISSUE THREAD

**Issue by jinyuttt** [hhblaze/Raft.Net#8]
remove LogEntry？

**Comment by hhblaze** [comment]
If you remove logEntry newly connected peers will not be able to restore the state of the database, nobody knows which peer will be chosen as a restoration point, so each peer should have it. Nevertheless, it is a point of optimization. Because LogEntry is a DBreeze table, it is possible to stop instance, to make records more compact, zip it and transfer as a file (table files) to the new peer. This RAFT.NET implementation is a basic point that can grow in any direction depending upon the needs.

**Comment by jinyuttt** [comment]
ok
